// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:702593551954:web:27f3801d9cc78ef1da998b',
    messagingSenderId: '702593551954',
    projectId: 'newssense-4483e',
    authDomain: 'newssense-4483e.firebaseapp.com',
    storageBucket: 'newssense-4483e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:702593551954:android:d138beb4b6fba7aeda998b',
    messagingSenderId: '702593551954',
    projectId: 'newssense-4483e',
    storageBucket: 'newssense-4483e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:702593551954:ios:e857a62c7fc8d667da998b',
    messagingSenderId: '702593551954',
    projectId: 'newssense-4483e',
    storageBucket: 'newssense-4483e.firebasestorage.app',
    iosBundleId: 'com.example.newsSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:702593551954:ios:e857a62c7fc8d667da998b',
    messagingSenderId: '702593551954',
    projectId: 'newssense-4483e',
    storageBucket: 'newssense-4483e.firebasestorage.app',
    iosBundleId: 'com.example.newsSense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:702593551954:web:9b78b20f97c3c3ccda998b',
    messagingSenderId: '702593551954',
    projectId: 'newssense-4483e',
    authDomain: 'newssense-4483e.firebaseapp.com',
    storageBucket: 'newssense-4483e.firebasestorage.app',
  );
}
